version: '3.8'

services:
  discord-gpt:
    build: .
    container_name: discord
    volumes:
      - ./app:/app  # Mount the app directory to /app
    environment:
      - OPENAI_SECRET=${OPENAI_SECRET}
      - DISCORD_ID=${DISCORD_ID}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_OWNER_ID=${DISCORD_OWNER_ID}
    depends_on:
      - db

  db:
    image: keinos/sqlite3
    user: root
    container_name: db
    volumes:
      - ./app:/var/lib/db  # Mount the app directory to /var/lib/db
      - ./schema.sql:/schema.sql  # schema.sql is outside the app directory
      - ./entrypoint.sh:/entrypoint.sh  # entrypoint.sh is outside the app directory
    entrypoint: ["/entrypoint.sh"]
    command: sh -c "sqlite3 /var/lib/db/main.db '.read /schema.sql'"

